<a href="https://colab.research.google.com/github/Minorito/CursoPandas/blob/main/Organizando_DataFrames(Sort).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [4]:
data = [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]

In [5]:
data

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
list('321')

['3', '2', '1']

In [9]:
df = pd.DataFrame(data, list('321'), list('ZYX'))
df

   Z  Y  X
3  1  2  3
2  4  5  6
1  7  8  9

In [23]:
df.sort_index(inplace = True)
df

   Z  Y  X
1  7  8  9
2  4  5  6
3  1  2  3

In [13]:
df.sort_index(inplace = True, axis=1)
df

   X  Y  Z
1  9  8  7
2  6  5  4
3  3  2  1

In [28]:
df.sort_values(by = ['X', 'Y'], inplace = True)
df

   Z  Y  X
3  1  2  3
2  4  5  6
1  7  8  9

In [18]:
df.sort_values(by = '3', axis=1, inplace = True)
df

   Z  Y  X
3  1  2  3
2  4  5  6
1  7  8  9